platform :ios, '8.0'
use_frameworks!
pod 'QorumLogs'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Nirvana_1' do
    pod 'Alamofire', '~> 3.4'
    end
